apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: scaleresources.com.ericsson.sec.scale.resource
spec:
  group: com.ericsson.sec.scale.resource
  versions:
  - name: v2
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          scaleLevel:
            type: string
        required:
          - scaleLevel
  - name: v1
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: object
        properties:
          scaleLevel:
            type: string
        required:
          - scaleLevel
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: scaleresources
    # singular name to be used as an alias on the CLI and for display
    singular: scaleresource
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: ScaleResource
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - scalersc